import { Toaster } from "sonner";
import "./globals.css";
import { SessionProvider } from 'next-auth/react'
import { auth } from "@/lib/auth";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth()
  return (
    <SessionProvider session={session}>  
    <html lang="en">
      <body className="h-screen font-secondary antialiased">

      <Toaster />
        {children}
      </body>
    </html>
    </SessionProvider>
  );
}
